// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLiTuyenXeBusDalat.Data;

#nullable disable

namespace QuanLiTuyenXeBusDalat.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20230309053156_AddTaiXe")]
    partial class AddTaiXe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLiTuyenXeBusDalat.Data.TaiXe", b =>
                {
                    b.Property<Guid>("MaTX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BangLai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Luong")
                        .HasColumnType("float");

                    b.Property<int>("MaXe")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBDHopDong")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("QueQuan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTX");

                    b.HasIndex("MaXe");

                    b.ToTable("TaiXe", (string)null);
                });

            modelBuilder.Entity("QuanLiTuyenXeBusDalat.Data.Xe", b =>
                {
                    b.Property<int>("MaXe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaXe"));

                    b.Property<string>("BienSo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChuKyBaoHanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("CongSuat")
                        .HasColumnType("real");

                    b.Property<string>("LoaiXe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySX")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoGhe")
                        .HasColumnType("int");

                    b.HasKey("MaXe");

                    b.ToTable("Xe");
                });

            modelBuilder.Entity("QuanLiTuyenXeBusDalat.Data.TaiXe", b =>
                {
                    b.HasOne("QuanLiTuyenXeBusDalat.Data.Xe", "Xe")
                        .WithMany("TaiXes")
                        .HasForeignKey("MaXe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Xe");
                });

            modelBuilder.Entity("QuanLiTuyenXeBusDalat.Data.Xe", b =>
                {
                    b.Navigation("TaiXes");
                });
#pragma warning restore 612, 618
        }
    }
}
